name: hod_madrid_py
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9

  # Scientific computing stack
  - numpy>=1.20
  - scipy>=1.7
  - matplotlib>=3.5

  # Numba for high-performance computing (CPU only)
  - numba

  # Data handling and I/O
  - h5py  

  #- typer
  #- loguru
  #- tqdm
  - ruff
  - pytest
  
  - pip
  - pip:
    #- python-dotenv
    - mkdocs